version: '3.9'
services:
  app:
      container_name: app_container
      build: .
      ports:
        - ${PORT}:${PORT}
      depends_on:
        - db
      volumes:
        - ./:/app
      networks: 
        - postgres
      environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_HOST: postgres
  db:
    container_name: postgres_container
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres
    volumes:
      - ./database:/var/lib/postgresql/data
networks:
  postgres:
    driver: bridge

